import { defineConfig } from 'vite';
import path from 'path';

export default defineConfig({
  resolve: {
    alias: {
      '@': path.resolve(__dirname, './src'),
      '@main': path.resolve(__dirname, './src/main'),
      '@domain': path.resolve(__dirname, './src/main/domain'),
      '@application': path.resolve(__dirname, './src/main/application'),
      '@adapters': path.resolve(__dirname, './src/main/adapters'),
      '@infrastructure': path.resolve(__dirname, './src/main/infrastructure'),
      '@shared': path.resolve(__dirname, './src/shared'),
    },
    conditions: ['node'],
  },
  build: {
    target: 'node18',
    outDir: 'dist/main',
    emptyOutDir: true,
    lib: {
      entry: path.resolve(__dirname, 'src/main/index.ts'),
      formats: ['cjs'],
      fileName: () => 'index.cjs',
    },
    rollupOptions: {
      external: [
        'electron',
        // OpenTelemetry is dev-only (loaded via a dev-gated dynamic import).
        // Externalised so its require-in-the-middle auto-instrumentation works
        // and the devDependency SDK never gets bundled into prod.
        /^@opentelemetry\//,
        '@libsql/client',
        '@libsql/client/sqlite3',
        'vectra',
        'electron-store',
        'electron-log',
        'nanoid',
        'jsdom',
        'font-list',
        'path',
        'fs',
        'fs/promises',
        'crypto',
        'os',
        'child_process',
        'readline',
        'vm',
        'url',
        'util',
        'http',
        'https',
        'stream',
        'zlib',
        'net',
        'tls',
        'dns',
        'assert',
        'node:path',
        'node:fs',
        'node:fs/promises',
        'node:crypto',
        'node:os',
        'node:vm',
        'node:url',
        'node:util',
        'node:http',
        'node:https',
        'node:stream',
        'node:zlib',
        'node:net',
        'node:tls',
        'node:dns',
        'node:assert',
        'node:child_process',
        'node:readline',
        'async_hooks',
        'node:async_hooks',
        'node:buffer',
        'node:string_decoder',
        'perf_hooks',
        'node:perf_hooks',
        'buffer',
        'string_decoder',
        'worker_threads',
        'node:worker_threads',
        // Watcher/libs
        'chokidar',
        'readdirp',
        'events',
        'node:events',
        'node:stream',
        'simple-git',
        'minipass',
        'glob',
        // Note: @xenova/transformers is loaded in a worker thread, not in main process
        // The worker has `self` defined, so no polyfill needed
        'sharp',
        // onnxruntime-node is a native (N-API) module — never bundle it.
        // Used by OnnxEchoCanceller via dynamic import in the main process.
        'onnxruntime-node',
      ],
    },
  },
});
