/**
 * MarkdownService - Converts between HTML and Markdown formats
 */

import TurndownService from 'turndown';
import { marked } from 'marked';
import { logger } from '../utils/logger';

/**
 * LRU cache entry for markdown parsing
 */
interface CacheEntry {
  html: string;
  mtime: number;
}

/**
 * Simple LRU cache for markdown to HTML conversion
 */
class MarkdownCache {
  private cache = new Map<string, CacheEntry>();
  private maxSize: number;

  constructor(maxSize = 100) {
    this.maxSize = maxSize;
  }

  get(key: string, mtime: number): string | null {
    const entry = this.cache.get(key);
    if (!entry) return null;

    // Invalidate if file was modified
    if (entry.mtime !== mtime) {
      this.cache.delete(key);
      return null;
    }

    // Move to end (most recently used)
    this.cache.delete(key);
    this.cache.set(key, entry);
    return entry.html;
  }

  set(key: string, html: string, mtime: number): void {
    // Remove oldest entry if at capacity
    if (this.cache.size >= this.maxSize) {
      const firstKey = this.cache.keys().next().value;
      if (firstKey) this.cache.delete(firstKey);
    }

    this.cache.set(key, { html, mtime });
  }

  clear(): void {
    this.cache.clear();
  }
}

export class MarkdownService {
  private turndownService: TurndownService;
  private parseCache = new MarkdownCache(100);

  constructor() {
    // Initialize Turndown service for HTML -> Markdown conversion
    this.turndownService = new TurndownService({
      headingStyle: 'atx',
      codeBlockStyle: 'fenced',
      bulletListMarker: '-',
      emDelimiter: '*',
      strongDelimiter: '**',
    });

    // Add custom rules for better conversion
    this.addCustomRules();
  }

  /**
   * Convert HTML to Markdown
   */
  htmlToMarkdown(html: string): string {
    if (!html || html.trim() === '') {
      return '';
    }

    try {
      // If running in a browser-like environment with a document, let Turndown
      // handle parsing the HTML string directly. In the Electron main process
      // (Node), there is no DOM, so Turndown cannot parse a string input and
      // will throw `ReferenceError: document is not defined`.
      if (typeof document !== 'undefined') {
        return this.turndownService.turndown(html);
      }

      // Node environment: perform a lightweight HTML → Markdown conversion
      // that covers the common tags generated by our editor. This avoids
      // introducing a heavy DOM shim (e.g., jsdom) in the main process.
      return simpleHtmlToMarkdown(html);
    } catch (error) {
      // In main process, avoid noisy logs during bulk sync. Fall back to the
      // original content so we never block saves.
      if (process?.env?.NODE_ENV !== 'test') {
        logger.warn('HTML→Markdown conversion failed, writing content as-is.');
      }
      return html;
    }
  }

  /**
   * Convert Markdown to HTML with caching
   * @param markdown - Markdown content to convert
   * @param cacheKey - Optional cache key (e.g., file path)
   * @param mtime - Optional file modification time in milliseconds
   */
  async markdownToHtml(markdown: string, cacheKey?: string, mtime?: number): Promise<string> {
    if (!markdown || markdown.trim() === '') {
      return '';
    }

    // Check cache if key and mtime provided
    if (cacheKey && mtime !== undefined) {
      const cached = this.parseCache.get(cacheKey, mtime);
      if (cached) return cached;
    }

    try {
      // Pre-process markdown to convert Logseq-style task items
      const processedMarkdown = this.preprocessLogseqTasksInMarkdown(markdown);

      // Configure marked
      marked.setOptions({
        gfm: true, // GitHub Flavored Markdown
        breaks: true, // Convert \n to <br>
      });

      const html = await marked.parse(processedMarkdown);

      // Cache result if key and mtime provided
      if (cacheKey && mtime !== undefined) {
        this.parseCache.set(cacheKey, html, mtime);
      }

      return html;
    } catch (error) {
      logger.error('Error converting Markdown to HTML:', error);
      return markdown; // Return original if conversion fails
    }
  }

  /**
   * Pre-process markdown to convert Logseq-style task items to custom HTML
   * This runs before marked.js parsing to inject task list structure
   * Converts both:
   *   - "TODO Task text" → task item with checkbox
   *   - "- TODO Task text" → task item with checkbox (in list)
   */
  private preprocessLogseqTasksInMarkdown(markdown: string): string {
    const taskStates = ['TODO', 'DOING', 'DONE', 'WAITING', 'HOLD', 'CANCELED', 'CANCELLED', 'IDEA'];
    const lines = markdown.split('\n');
    const result: string[] = [];
    let inTaskList = false;

    for (let i = 0; i < lines.length; i++) {
      const line = lines[i];

      // Match TODO items with OR without list markers
      // Pattern 1: "TODO Task text" (standalone)
      const standaloneTaskMatch = line.match(new RegExp(`^(\\s*)(${taskStates.join('|')})\\s+(.+)$`, 'i'));

      // Pattern 2: "- TODO Task text" or "* TODO Task text" (in list)
      const listTaskMatch = line.match(new RegExp(`^(\\s*)[-*]\\s+(${taskStates.join('|')})\\s+(.+)$`, 'i'));

      const taskMatch = listTaskMatch || standaloneTaskMatch;
      const isListTask = !!listTaskMatch;

      if (taskMatch) {
        const indent = taskMatch[1];
        const state = taskMatch[2].toLowerCase();
        const normalizedState = state === 'cancelled' ? 'canceled' : state;
        const taskText = taskMatch[3];
        const isDone = normalizedState === 'done' || normalizedState === 'canceled';

        // Start task list if not already in one
        if (!inTaskList) {
          result.push('<ul data-type="taskList">');
          inTaskList = true;
        }

        // Add task item
        result.push(`<li data-type="taskItem" data-state="${normalizedState}" data-checked="${isDone}"><p>${taskText}</p></li>`);
      } else {
        // Close task list if we were in one
        if (inTaskList) {
          result.push('</ul>');
          inTaskList = false;
        }
        result.push(line);
      }
    }

    // Close task list if still open
    if (inTaskList) {
      result.push('</ul>');
    }

    return result.join('\n');
  }

  /**
   * Clear the markdown parse cache
   */
  clearCache(): void {
    this.parseCache.clear();
  }

  /**
   * Add custom Turndown rules
   */
  private addCustomRules(): void {
    // Handle Logseq-style task items with states
    this.turndownService.addRule('logseqTaskItem', {
      filter: (node) => {
        return (
          node.nodeName === 'LI' &&
          node.getAttribute('data-type') === 'taskItem' &&
          node.hasAttribute('data-state')
        );
      },
      replacement: (content, node) => {
        const state = node.getAttribute('data-state') || 'todo';
        const stateLabel = state.toUpperCase();

        // Extract the text content without the button
        const contentDiv = node.querySelector('div') || node.querySelector('p');
        const textContent = contentDiv ? contentDiv.textContent || '' : content;

        // Save as list-style TODO item with dash prefix for consistency
        return `- ${stateLabel} ${textContent.trim()}\n`;
      },
    });

    // Handle task list wrapper
    this.turndownService.addRule('logseqTaskList', {
      filter: (node) => {
        return (
          node.nodeName === 'UL' &&
          node.getAttribute('data-type') === 'taskList'
        );
      },
      replacement: (content, node) => {
        return content;
      },
    });

    // Preserve highlight spans
    this.turndownService.addRule('highlight', {
      filter: (node) => {
        return (
          node.nodeName === 'MARK' ||
          (node.nodeName === 'SPAN' && node.classList && node.classList.contains('bg-accent'))
        );
      },
      replacement: (content) => {
        return `==${content}==`; // Use standard highlight syntax
      },
    });

    // Handle code blocks with language
    this.turndownService.addRule('fencedCodeBlock', {
      filter: (node, options): boolean => {
        return (
          node.nodeName === 'PRE' && node.firstChild !== null && node.firstChild.nodeName === 'CODE'
        );
      },
      replacement: (content, node, options) => {
        const codeElement = node.firstChild as HTMLElement;
        const className = codeElement.className || '';

        // Try to extract language from class name
        let language = className.replace('language-', '').replace('hljs', '').replace('code-block', '').trim();

        // If no language in class, check for data-language attribute on parent wrapper
        if (!language) {
          let parent = node.parentElement;
          while (parent) {
            const dataLang = parent.getAttribute('data-language');
            if (dataLang) {
              language = dataLang;
              break;
            }
            parent = parent.parentElement;
          }
        }

        const code = codeElement.textContent || '';
        const fence = options.fence || '```';

        return `\n\n${fence}${language}\n${code}\n${fence}\n\n`;
      },
    });

    // Handle our custom code block wrapper structure
    this.turndownService.addRule('customCodeBlockWrapper', {
      filter: (node): boolean => {
        return (
          node.nodeName === 'DIV' &&
          node.classList &&
          node.classList.contains('code-block-wrapper')
        );
      },
      replacement: (content, node) => {
        // Find the pre > code element
        const preElement = node.querySelector('pre');
        const codeElement = preElement?.querySelector('code');

        if (!preElement || !codeElement) {
          return content;
        }

        // Try to get language from select element or data attribute
        let language = '';
        const selectElement = node.querySelector('select') as HTMLSelectElement;
        if (selectElement && selectElement.value) {
          language = selectElement.value;
        }

        const code = codeElement.textContent || '';
        const fence = '```';

        return `\n\n${fence}${language}\n${code}\n${fence}\n\n`;
      },
    });
  }

  /**
   * Sanitize filename from title
   */
  sanitizeFilename(title: string): string {
    return title
      .replace(/[/\\?%*:|"<>]/g, '-') // Replace invalid chars
      .replace(/\s+/g, ' ') // Normalize whitespace
      .trim()
      .substring(0, 200); // Limit length
  }

  /**
   * Generate filename from title
   */
  generateFilename(title: string, extension: string = '.md'): string {
    const sanitized = this.sanitizeFilename(title || 'Untitled');
    return `${sanitized}${extension}`;
  }

  /**
   * Extract title from markdown content (first heading or first line)
   */
  extractTitle(markdown: string): string {
    if (!markdown || markdown.trim() === '') {
      return 'Untitled';
    }

    const lines = markdown.split('\n');

    // Look for first heading
    for (const line of lines) {
      const headingMatch = line.match(/^#+\s+(.+)$/);
      if (headingMatch) {
        return headingMatch[1].trim();
      }
    }

    // Fall back to first non-empty line
    for (const line of lines) {
      const trimmed = line.trim();
      if (trimmed !== '') {
        return trimmed.substring(0, 100); // Limit to 100 chars
      }
    }

    return 'Untitled';
  }
}

// Singleton instance
let instance: MarkdownService | null = null;

/**
 * Get or create markdown service instance
 */
export function getMarkdownService(): MarkdownService {
  if (!instance) {
    instance = new MarkdownService();
  }
  return instance;
}

/**
 * Minimal HTML → Markdown converter for Node (no DOM available).
 * Handles common tags we generate: headings, paragraphs, strong/em, links,
 * images, lists, breaks, inline and fenced code blocks.
 */
function simpleHtmlToMarkdown(input: string): string {
  let out = input;

  // Normalize whitespace around block tags
  out = out.replace(/\r\n/g, '\n');

  // Code blocks: <pre><code class="language-xyz">...</code></pre>
  out = out.replace(
    /<pre>\s*<code([^>]*)>([\s\S]*?)<\/code>\s*<\/pre>/gi,
    (_, attrs: string, code: string) => {
      const langMatch = attrs.match(/class=["']?[^"']*language-([\w-]+)/i);
      const lang = langMatch ? langMatch[1] : '';
      // Decode HTML entities inside code
      const decoded = decodeHtmlEntities(code);
      return `\n\n\`\`\`${lang}\n${decoded}\n\`\`\`\n\n`;
    },
  );

  // Headings
  for (let i = 6; i >= 1; i--) {
    const re = new RegExp(`<h${i}[^>]*>([\n\s\S]*?)<\\/h${i}>`, 'gi');
    out = out.replace(
      re,
      (_, text: string) => `\n\n${'#'.repeat(i)} ${stripTags(text).trim()}\n\n`,
    );
  }

  // Paragraphs
  out = out.replace(
    /<p[^>]*>([\s\S]*?)<\/p>/gi,
    (_, text: string) => `\n\n${stripTags(text).trim()}\n\n`,
  );

  // Line breaks
  out = out.replace(/<br\s*\/?>(\s*)/gi, `\n`);

  // Task lists with Logseq-style states (WITH dash prefix for consistency)
  out = out.replace(
    /<li[^>]*data-type=["']taskItem["'][^>]*data-state=["']([^"']+)["'][^>]*>([\s\S]*?)<\/li>/gi,
    (_, state: string, content: string) => {
      const stateLabel = state.toUpperCase();
      // Remove the button element and extract text from div/p
      const textContent = content
        .replace(/<button[^>]*>[\s\S]*?<\/button>/gi, '')
        .replace(/<div[^>]*>([\s\S]*?)<\/div>/gi, '$1')
        .replace(/<p[^>]*>([\s\S]*?)<\/p>/gi, '$1')
        .trim();
      // Save as list-style TODO item with dash prefix for consistency
      return `- ${stateLabel} ${stripTags(textContent)}\n`;
    },
  );

  // Unordered lists
  out = out.replace(/<ul[^>]*>([\s\s\S]*?)<\/ul>/gi, (_, inner: string) => {
    const items = inner
      .replace(/\n/g, ' ')
      .split(/<li[^>]*>/i)
      .map((s) => s.replace(/<\/li>/gi, '').trim())
      .filter(Boolean);
    return `\n\n${items.map((it) => `- ${stripTags(it)}`).join('\n')}\n\n`;
  });

  // Ordered lists
  out = out.replace(/<ol[^>]*>([\s\S]*?)<\/ol>/gi, (_, inner: string) => {
    const items = inner
      .replace(/\n/g, ' ')
      .split(/<li[^>]*>/i)
      .map((s) => s.replace(/<\/li>/gi, '').trim())
      .filter(Boolean);
    return `\n\n${items.map((it, idx) => `${idx + 1}. ${stripTags(it)}`).join('\n')}\n\n`;
  });

  // Images
  out = out.replace(
    /<img\s+[^>]*src=["']([^"']+)["'][^>]*alt=["']([^"']*)["'][^>]*\/?>(?:<\/img>)?/gi,
    (_, src: string, alt: string) => `![${alt}](${src})`,
  );
  out = out.replace(
    /<img\s+[^>]*alt=["']([^"']*)["'][^>]*src=["']([^"']+)["'][^>]*\/?>(?:<\/img>)?/gi,
    (_, alt: string, src: string) => `![${alt}](${src})`,
  );

  // Links
  out = out.replace(
    /<a\s+[^>]*href=["']([^"']+)["'][^>]*>([\s\S]*?)<\/a>/gi,
    (_, href: string, text: string) => `[${stripTags(text)}](${href})`,
  );

  // Inline code
  out = out.replace(
    /<code[^>]*>([\s\S]*?)<\/code>/gi,
    (_, code: string) => `\`${stripTags(decodeHtmlEntities(code))}\``,
  );

  // Emphasis and strong
  out = out.replace(/<strong[^>]*>([\s\S]*?)<\/strong>/gi, (_, t: string) => `**${stripTags(t)}**`);
  out = out.replace(/<b[^>]*>([\s\S]*?)<\/b>/gi, (_, t: string) => `**${stripTags(t)}**`);
  out = out.replace(/<em[^>]*>([\s\S]*?)<\/em>/gi, (_, t: string) => `*${stripTags(t)}*`);
  out = out.replace(/<i[^>]*>([\s\S]*?)<\/i>/gi, (_, t: string) => `*${stripTags(t)}*`);

  // Finally strip any remaining tags
  out = stripTags(out);

  // Collapse excess blank lines
  out = out.replace(/\n{3,}/g, '\n\n').trim();

  return out;
}

function stripTags(s: string): string {
  return s.replace(/<[^>]+>/g, '');
}

function decodeHtmlEntities(s: string): string {
  return s
    .replace(/&lt;/g, '<')
    .replace(/&gt;/g, '>')
    .replace(/&amp;/g, '&')
    .replace(/&quot;/g, '"')
    .replace(/&#39;/g, "'");
}
