/**
 * MarkdownService - Converts between HTML and Markdown formats
 */

import TurndownService from 'turndown';
import { marked } from 'marked';

export class MarkdownService {
  private turndownService: TurndownService;

  constructor() {
    // Initialize Turndown service for HTML -> Markdown conversion
    this.turndownService = new TurndownService({
      headingStyle: 'atx',
      codeBlockStyle: 'fenced',
      bulletListMarker: '-',
      emDelimiter: '*',
      strongDelimiter: '**',
    });

    // Add custom rules for better conversion
    this.addCustomRules();
  }

  /**
   * Convert HTML to Markdown
   */
  htmlToMarkdown(html: string): string {
    if (!html || html.trim() === '') {
      return '';
    }

    try {
      // If running in a browser-like environment with a document, let Turndown
      // handle parsing the HTML string directly. In the Electron main process
      // (Node), there is no DOM, so Turndown cannot parse a string input and
      // will throw `ReferenceError: document is not defined`.
      if (typeof document !== 'undefined') {
        return this.turndownService.turndown(html);
      }

      // Node environment: perform a lightweight HTML → Markdown conversion
      // that covers the common tags generated by our editor. This avoids
      // introducing a heavy DOM shim (e.g., jsdom) in the main process.
      return simpleHtmlToMarkdown(html);
    } catch (error) {
      // In main process, avoid noisy logs during bulk sync. Fall back to the
      // original content so we never block saves.
      if (process?.env?.NODE_ENV !== 'test') {
        console.warn('HTML→Markdown conversion failed, writing content as-is.');
      }
      return html;
    }
  }

  /**
   * Convert Markdown to HTML
   */
  async markdownToHtml(markdown: string): Promise<string> {
    if (!markdown || markdown.trim() === '') {
      return '';
    }

    try {
      // Configure marked options
      marked.setOptions({
        gfm: true, // GitHub Flavored Markdown
        breaks: true, // Convert \n to <br>
      });

      return await marked.parse(markdown);
    } catch (error) {
      console.error('Error converting Markdown to HTML:', error);
      return markdown; // Return original if conversion fails
    }
  }

  /**
   * Add custom Turndown rules
   */
  private addCustomRules(): void {
    // Preserve highlight spans
    this.turndownService.addRule('highlight', {
      filter: (node) => {
        return (
          node.nodeName === 'MARK' ||
          (node.nodeName === 'SPAN' &&
            node.classList &&
            node.classList.contains('bg-accent'))
        );
      },
      replacement: (content) => {
        return `==${content}==`; // Use standard highlight syntax
      },
    });

    // Handle code blocks with language
    this.turndownService.addRule('fencedCodeBlock', {
      filter: (node, options): boolean => {
        return (
          node.nodeName === 'PRE' &&
          node.firstChild !== null &&
          node.firstChild.nodeName === 'CODE'
        );
      },
      replacement: (content, node, options) => {
        const codeElement = node.firstChild as HTMLElement;
        const className = codeElement.className || '';
        const language = className.replace('language-', '').replace('code-block', '').trim();

        const code = codeElement.textContent || '';
        const fence = options.fence || '```';

        return `\n\n${fence}${language}\n${code}\n${fence}\n\n`;
      },
    });
  }

  /**
   * Sanitize filename from title
   */
  sanitizeFilename(title: string): string {
    return title
      .replace(/[/\\?%*:|"<>]/g, '-') // Replace invalid chars
      .replace(/\s+/g, ' ') // Normalize whitespace
      .trim()
      .substring(0, 200); // Limit length
  }

  /**
   * Generate filename from title
   */
  generateFilename(title: string, extension: string = '.md'): string {
    const sanitized = this.sanitizeFilename(title || 'Untitled');
    return `${sanitized}${extension}`;
  }

  /**
   * Extract title from markdown content (first heading or first line)
   */
  extractTitle(markdown: string): string {
    if (!markdown || markdown.trim() === '') {
      return 'Untitled';
    }

    const lines = markdown.split('\n');

    // Look for first heading
    for (const line of lines) {
      const headingMatch = line.match(/^#+\s+(.+)$/);
      if (headingMatch) {
        return headingMatch[1].trim();
      }
    }

    // Fall back to first non-empty line
    for (const line of lines) {
      const trimmed = line.trim();
      if (trimmed !== '') {
        return trimmed.substring(0, 100); // Limit to 100 chars
      }
    }

    return 'Untitled';
  }
}

// Singleton instance
let instance: MarkdownService | null = null;

/**
 * Get or create markdown service instance
 */
export function getMarkdownService(): MarkdownService {
  if (!instance) {
    instance = new MarkdownService();
  }
  return instance;
}

/**
 * Minimal HTML → Markdown converter for Node (no DOM available).
 * Handles common tags we generate: headings, paragraphs, strong/em, links,
 * images, lists, breaks, inline and fenced code blocks.
 */
function simpleHtmlToMarkdown(input: string): string {
  let out = input;

  // Normalize whitespace around block tags
  out = out.replace(/\r\n/g, '\n');

  // Code blocks: <pre><code class="language-xyz">...</code></pre>
  out = out.replace(
    /<pre>\s*<code([^>]*)>([\s\S]*?)<\/code>\s*<\/pre>/gi,
    (_, attrs: string, code: string) => {
      const langMatch = attrs.match(/class=["']?[^"']*language-([\w-]+)/i);
      const lang = langMatch ? langMatch[1] : '';
      // Decode HTML entities inside code
      const decoded = decodeHtmlEntities(code);
      return `\n\n\`\`\`${lang}\n${decoded}\n\`\`\`\n\n`;
    },
  );

  // Headings
  for (let i = 6; i >= 1; i--) {
    const re = new RegExp(`<h${i}[^>]*>([\n\s\S]*?)<\\/h${i}>`, 'gi');
    out = out.replace(re, (_, text: string) => `\n\n${'#'.repeat(i)} ${stripTags(text).trim()}\n\n`);
  }

  // Paragraphs
  out = out.replace(/<p[^>]*>([\s\S]*?)<\/p>/gi, (_, text: string) => `\n\n${stripTags(text).trim()}\n\n`);

  // Line breaks
  out = out.replace(/<br\s*\/?>(\s*)/gi, `\n`);

  // Unordered lists
  out = out.replace(/<ul[^>]*>([\s\s\S]*?)<\/ul>/gi, (_, inner: string) => {
    const items = inner
      .replace(/\n/g, ' ')
      .split(/<li[^>]*>/i)
      .map((s) => s.replace(/<\/li>/gi, '').trim())
      .filter(Boolean);
    return `\n\n${items.map((it) => `- ${stripTags(it)}`).join('\n')}\n\n`;
  });

  // Ordered lists
  out = out.replace(/<ol[^>]*>([\s\S]*?)<\/ol>/gi, (_, inner: string) => {
    const items = inner
      .replace(/\n/g, ' ')
      .split(/<li[^>]*>/i)
      .map((s) => s.replace(/<\/li>/gi, '').trim())
      .filter(Boolean);
    return `\n\n${items.map((it, idx) => `${idx + 1}. ${stripTags(it)}`).join('\n')}\n\n`;
  });

  // Images
  out = out.replace(
    /<img\s+[^>]*src=["']([^"']+)["'][^>]*alt=["']([^"']*)["'][^>]*\/?>(?:<\/img>)?/gi,
    (_, src: string, alt: string) => `![${alt}](${src})`,
  );
  out = out.replace(
    /<img\s+[^>]*alt=["']([^"']*)["'][^>]*src=["']([^"']+)["'][^>]*\/?>(?:<\/img>)?/gi,
    (_, alt: string, src: string) => `![${alt}](${src})`,
  );

  // Links
  out = out.replace(
    /<a\s+[^>]*href=["']([^"']+)["'][^>]*>([\s\S]*?)<\/a>/gi,
    (_, href: string, text: string) => `[${stripTags(text)}](${href})`,
  );

  // Inline code
  out = out.replace(/<code[^>]*>([\s\S]*?)<\/code>/gi, (_, code: string) => `\`${stripTags(decodeHtmlEntities(code))}\``);

  // Emphasis and strong
  out = out.replace(/<strong[^>]*>([\s\S]*?)<\/strong>/gi, (_, t: string) => `**${stripTags(t)}**`);
  out = out.replace(/<b[^>]*>([\s\S]*?)<\/b>/gi, (_, t: string) => `**${stripTags(t)}**`);
  out = out.replace(/<em[^>]*>([\s\S]*?)<\/em>/gi, (_, t: string) => `*${stripTags(t)}*`);
  out = out.replace(/<i[^>]*>([\s\S]*?)<\/i>/gi, (_, t: string) => `*${stripTags(t)}*`);

  // Finally strip any remaining tags
  out = stripTags(out);

  // Collapse excess blank lines
  out = out.replace(/\n{3,}/g, '\n\n').trim();

  return out;
}

function stripTags(s: string): string {
  return s.replace(/<[^>]+>/g, '');
}

function decodeHtmlEntities(s: string): string {
  return s
    .replace(/&lt;/g, '<')
    .replace(/&gt;/g, '>')
    .replace(/&amp;/g, '&')
    .replace(/&quot;/g, '"')
    .replace(/&#39;/g, "'");
}
