/**
 * MarkdownService - Converts between HTML and Markdown formats
 */

import TurndownService from 'turndown';
import { marked } from 'marked';
import { logger } from '../utils/logger';

/**
 * LRU cache entry for markdown parsing
 */
interface CacheEntry {
  html: string;
  mtime: number;
}

/**
 * Simple LRU cache for markdown to HTML conversion
 */
class MarkdownCache {
  private readonly cache = new Map<string, CacheEntry>();
  private readonly maxSize: number;

  constructor(maxSize = 100) {
    this.maxSize = maxSize;
  }

  get(key: string, mtime: number): string | null {
    const entry = this.cache.get(key);
    if (!entry) return null;

    // Invalidate if file was modified
    if (entry.mtime !== mtime) {
      this.cache.delete(key);
      return null;
    }

    // Move to end (most recently used)
    this.cache.delete(key);
    this.cache.set(key, entry);
    return entry.html;
  }

  set(key: string, html: string, mtime: number): void {
    // Remove oldest entry if at capacity
    if (this.cache.size >= this.maxSize) {
      const firstKey = this.cache.keys().next().value;
      if (firstKey) this.cache.delete(firstKey);
    }

    this.cache.set(key, { html, mtime });
  }

  clear(): void {
    this.cache.clear();
  }
}

export class MarkdownService {
  private readonly turndownService: TurndownService;
  private readonly parseCache = new MarkdownCache(100);

  constructor() {
    // Initialize Turndown service for HTML -> Markdown conversion
    this.turndownService = new TurndownService({
      headingStyle: 'atx',
      codeBlockStyle: 'fenced',
      bulletListMarker: '-',
      emDelimiter: '*',
      strongDelimiter: '**',
    });

    // Add custom rules for better conversion
    this.addCustomRules();
  }

  /**
   * Convert HTML to Markdown
   */
  htmlToMarkdown(html: string): string {
    if (!html || html.trim() === '') {
      return '';
    }

    try {
      // If running in a browser-like environment with a document, let Turndown
      // handle parsing the HTML string directly. In the Electron main process
      // (Node), there is no DOM, so Turndown cannot parse a string input and
      // will throw `ReferenceError: document is not defined`.
      if (typeof document !== 'undefined') {
        return this.turndownService.turndown(html);
      }

      // Node environment: perform a lightweight HTML → Markdown conversion
      // that covers the common tags generated by our editor. This avoids
      // introducing a heavy DOM shim (e.g., jsdom) in the main process.
      return simpleHtmlToMarkdown(html);
    } catch {
      // In main process, avoid noisy logs during bulk sync. Fall back to the
      // original content so we never block saves.
      if (process?.env?.NODE_ENV !== 'test') {
        logger.warn('HTML→Markdown conversion failed, writing content as-is.');
      }
      return html;
    }
  }

  /**
   * Convert Markdown to HTML with caching
   * @param markdown - Markdown content to convert
   * @param cacheKey - Optional cache key (e.g., file path)
   * @param mtime - Optional file modification time in milliseconds
   */
  async markdownToHtml(markdown: string, cacheKey?: string, mtime?: number): Promise<string> {
    if (!markdown || markdown.trim() === '') {
      return '';
    }

    // Check cache if key and mtime provided
    if (cacheKey && mtime !== undefined) {
      const cached = this.parseCache.get(cacheKey, mtime);
      if (cached) return cached;
    }

    try {
      // Pre-process markdown to handle special syntax (tasks, note links)
      const processedMarkdown = this.preprocessMarkdown(markdown);

      // Configure marked
      marked.setOptions({
        gfm: true, // GitHub Flavored Markdown
        breaks: true, // Convert \n to <br>
      });

      const html = await marked.parse(processedMarkdown);

      // Cache result if key and mtime provided
      if (cacheKey && mtime !== undefined) {
        this.parseCache.set(cacheKey, html, mtime);
      }

      return html;
    } catch (error) {
      logger.error('Error converting Markdown to HTML:', error);
      return markdown; // Return original if conversion fails
    }
  }

  /**
   * Pre-process markdown to handle special syntax before marked.js parsing
   * - Indented blocks (tabs → data-indent)
   * - Logseq-style task items
   * - [[note name]] wiki-style links
   */
  private preprocessMarkdown(markdown: string): string {
    let result = markdown;

    // Convert leading tabs to indented paragraphs/headings
    result = this.preprocessIndentedBlocks(result);

    // Convert [[note name]] to custom HTML spans
    // The note ID will be resolved in the frontend
    result = result.replaceAll(/\[\[([^\]]{1,500})\]\]/g, (_: string, noteName: string) => {
      return `<span data-type="note-link" data-title="${escapeHtml(noteName)}">${escapeHtml(noteName)}</span>`;
    });

    // Then process Logseq task items
    result = this.preprocessLogseqTasksInMarkdown(result);

    return result;
  }

  /**
   * Pre-process indented blocks (tabs at start of line → data-indent attribute)
   */
  private preprocessIndentedBlocks(markdown: string): string {
    const lines = markdown.split('\n');
    const result: string[] = [];

    for (const line of lines) {
      // Count leading tabs (bounded quantifiers prevent ReDoS)
      const tabMatch = /^(\t{1,20})(.{0,10000})$/.exec(line);
      if (tabMatch) {
        const indent = tabMatch[1].length;
        const content = tabMatch[2];

        // Check if it's a heading (bounded quantifiers prevent ReDoS)
        const headingMatch = /^(#{1,6})\s{1,10}(.{1,500})$/.exec(content);
        if (headingMatch) {
          const level = headingMatch[1].length;
          const text = headingMatch[2];
          result.push(`<h${level} data-indent="${indent}" style="margin-left: ${indent * 24}px">${escapeHtml(text)}</h${level}>`);
        } else if (content.trim()) {
          // Regular indented paragraph
          result.push(`<p data-indent="${indent}" style="margin-left: ${indent * 24}px">${escapeHtml(content)}</p>`);
        } else {
          result.push(line);
        }
      } else {
        result.push(line);
      }
    }

    return result.join('\n');
  }

  /**
   * Pre-process markdown to convert Logseq-style task items to custom HTML
   * This runs before marked.js parsing to inject task list structure
   * Converts both:
   *   - Standalone task items (e.g. "DOING Task text") → task item with checkbox
   *   - List task items (e.g. "- DONE Task text") → task item with checkbox (in list)
   */
  private preprocessLogseqTasksInMarkdown(markdown: string): string {
    const taskStates = ['TODO', 'DOING', 'DONE', 'WAITING', 'HOLD', 'CANCELED', 'CANCELLED', 'IDEA'];
    const lines = markdown.split('\n');
    const result: string[] = [];
    let inTaskList = false;

    for (const line of lines) {
      // Match task items with OR without list markers
      // Pattern 1: "DOING Task text" (standalone task state)
      const standaloneTaskMatch = new RegExp(String.raw`^(\s*)(${taskStates.join('|')})\s+(.+)$`, 'i').exec(line);

      // Pattern 2: "- DONE Task text" or "* DOING Task text" (task in list)
      const listTaskMatch = new RegExp(String.raw`^(\s*)[-*]\s+(${taskStates.join('|')})\s+(.+)$`, 'i').exec(line);

      const taskMatch = listTaskMatch || standaloneTaskMatch;

      if (taskMatch) {
        const state = taskMatch[2].toLowerCase();
        const normalizedState = state === 'cancelled' ? 'canceled' : state;
        const taskText = taskMatch[3];
        const isDone = normalizedState === 'done' || normalizedState === 'canceled';

        // Start task list if not already in one
        if (!inTaskList) {
          result.push('<ul data-type="taskList">');
          inTaskList = true;
        }

        // Add task item
        result.push(`<li data-type="taskItem" data-state="${normalizedState}" data-checked="${isDone}"><p>${taskText}</p></li>`);
      } else {
        // Close task list if we were in one
        if (inTaskList) {
          result.push('</ul>');
          inTaskList = false;
        }
        result.push(line);
      }
    }

    // Close task list if still open
    if (inTaskList) {
      result.push('</ul>');
    }

    return result.join('\n');
  }

  /**
   * Clear the markdown parse cache
   */
  clearCache(): void {
    this.parseCache.clear();
  }

  /**
   * Add custom Turndown rules
   */
  private addCustomRules(): void {
    // Handle indented paragraphs (Logseq-style blocks)
    this.turndownService.addRule('indentedParagraph', {
      filter: (node: Node): boolean => {
        if (node.nodeName !== 'P') return false;
        const dataset = (node as HTMLElement).dataset;
        return dataset.indent !== undefined && Number.parseInt(dataset.indent || '0', 10) > 0;
      },
      replacement: (content: string, node: Node): string => {
        const indent = Number.parseInt((node as HTMLElement).dataset.indent || '0', 10);
        const tabs = '\t'.repeat(indent);
        return `\n\n${tabs}${content.trim()}\n\n`;
      },
    });

    // Handle indented headings
    this.turndownService.addRule('indentedHeading', {
      filter: (node: Node): boolean => {
        if (!/^H[1-6]$/.test(node.nodeName)) return false;
        const dataset = (node as HTMLElement).dataset;
        return dataset.indent !== undefined && Number.parseInt(dataset.indent || '0', 10) > 0;
      },
      replacement: (content: string, node: Node): string => {
        const indent = Number.parseInt((node as HTMLElement).dataset.indent || '0', 10);
        const level = Number.parseInt(node.nodeName.charAt(1), 10);
        const tabs = '\t'.repeat(indent);
        return `\n\n${tabs}${'#'.repeat(level)} ${content.trim()}\n\n`;
      },
    });

    // Handle Logseq-style task items with states
    this.turndownService.addRule('logseqTaskItem', {
      filter: (node: Node): boolean => {
        if (node.nodeName !== 'LI') return false;
        const dataset = (node as HTMLElement).dataset;
        return dataset.type === 'taskItem' && dataset.state !== undefined;
      },
      replacement: (content: string, node: Node): string => {
        const state = (node as HTMLElement).dataset.state || 'todo';
        const stateLabel = state.toUpperCase();

        // Extract the text content without the button
        const contentDiv = (node as HTMLElement).querySelector('div') || (node as HTMLElement).querySelector('p');
        const textContent = contentDiv ? contentDiv.textContent || '' : content;

        // Save as list-style task item with dash prefix for consistency
        return `- ${stateLabel} ${textContent.trim()}\n`;
      },
    });

    // Handle task list wrapper
    this.turndownService.addRule('logseqTaskList', {
      filter: (node: Node): boolean => {
        if (node.nodeName !== 'UL') return false;
        return (node as HTMLElement).dataset.type === 'taskList';
      },
      replacement: (content: string): string => {
        return content;
      },
    });

    // Preserve highlight spans
    this.turndownService.addRule('highlight', {
      filter: (node) => {
        return (
          node.nodeName === 'MARK' ||
          (node.nodeName === 'SPAN' && node.classList?.contains('bg-accent'))
        );
      },
      replacement: (content) => {
        return `==${content}==`; // Use standard highlight syntax
      },
    });

    // Handle code blocks with language
    this.turndownService.addRule('fencedCodeBlock', {
      filter: (node: Node): boolean => {
        return node.nodeName === 'PRE' && node.firstChild !== null && node.firstChild.nodeName === 'CODE';
      },
      replacement: (content: string, node: Node, options): string => {
        const codeElement = node.firstChild as HTMLElement;
        const className = codeElement.className || '';

        // Try to extract language from class name
        let language = className.replaceAll('language-', '').replaceAll('hljs', '').replaceAll('code-block', '').trim();

        // If no language in class, check for data-language attribute on parent wrapper
        if (!language) {
          let parent = (node as HTMLElement).parentElement;
          while (parent) {
            const dataLang = parent.dataset?.language;
            if (dataLang) {
              language = dataLang;
              break;
            }
            parent = parent.parentElement;
          }
        }

        const code = codeElement.textContent || '';
        const fence = options.fence || '```';

        return `\n\n${fence}${language}\n${code}\n${fence}\n\n`;
      },
    });

    // Handle [[note name]] wiki-style links
    this.turndownService.addRule('noteLink', {
      filter: (node: Node): boolean => {
        if (node.nodeName !== 'SPAN') return false;
        return (node as HTMLElement).dataset.type === 'note-link';
      },
      replacement: (content: string, node: Node): string => {
        const title = (node as HTMLElement).dataset.title || content;
        return `[[${title}]]`;
      },
    });

    // Handle our custom code block wrapper structure
    this.turndownService.addRule('customCodeBlockWrapper', {
      filter: (node): boolean => {
        return (
          node.nodeName === 'DIV' &&
          node.classList?.contains('code-block-wrapper')
        );
      },
      replacement: (content, node) => {
        // Find the pre > code element
        const preElement = node.querySelector('pre');
        const codeElement = preElement?.querySelector('code');

        if (!preElement || !codeElement) {
          return content;
        }

        // Try to get language from select element or data attribute
        let language = '';
        const selectElement = node.querySelector('select') as HTMLSelectElement;
        if (selectElement?.value) {
          language = selectElement.value;
        }

        const code = codeElement.textContent || '';
        const fence = '```';

        return `\n\n${fence}${language}\n${code}\n${fence}\n\n`;
      },
    });
  }

  /**
   * Sanitize filename from title
   */
  sanitizeFilename(title: string): string {
    return title
      .replaceAll(/[/\\?%*:|"<>]/g, '-') // Replace invalid chars
      .replaceAll(/\s+/g, ' ') // Normalize whitespace
      .trim()
      .substring(0, 200); // Limit length
  }

  /**
   * Generate filename from title
   */
  generateFilename(title: string, extension: string = '.md'): string {
    const sanitized = this.sanitizeFilename(title || 'Untitled');
    return `${sanitized}${extension}`;
  }

  /**
   * Convert HTML to plain text (strip all tags and decode entities)
   * Useful for generating embeddings from note content
   */
  htmlToPlainText(html: string): string {
    if (!html || html.trim() === '') {
      return '';
    }

    // First convert to markdown to preserve structure
    const markdown = this.htmlToMarkdown(html);

    // Then strip markdown syntax to get plain text
    return markdown
      .replaceAll(/#{1,6}\s+/g, '') // Remove heading markers
      .replaceAll(/\*\*([^*]+)\*\*/g, '$1') // Bold
      .replaceAll(/\*([^*]+)\*/g, '$1') // Italic
      .replaceAll(/`([^`]+)`/g, '$1') // Inline code
      .replaceAll(/```[\s\S]*?```/g, '') // Code blocks
      .replaceAll(/\[([^\]]+)\]\([^)]+\)/g, '$1') // Links
      .replaceAll(/!\[([^\]]*)\]\([^)]+\)/g, '$1') // Images
      .replaceAll(/\[\[([^\]]+)\]\]/g, '$1') // Wiki links
      .replaceAll(/^[-*+]\s+/gm, '') // Unordered lists
      .replaceAll(/^\d+\.\s+/gm, '') // Ordered lists
      .replaceAll(/^>\s+/gm, '') // Blockquotes
      .replaceAll(/\n{3,}/g, '\n\n') // Collapse blank lines
      .trim();
  }

  /**
   * Extract title from markdown content (first heading or first line)
   */
  extractTitle(markdown: string): string {
    if (!markdown || markdown.trim() === '') {
      return 'Untitled';
    }

    const lines = markdown.split('\n');

    // Look for first heading (limit quantifiers to prevent ReDoS)
    for (const line of lines) {
      const headingMatch = /^#{1,6}\s{1,10}(.{1,500})$/.exec(line);
      if (headingMatch) {
        return headingMatch[1].trim();
      }
    }

    // Fall back to first non-empty line
    for (const line of lines) {
      const trimmed = line.trim();
      if (trimmed !== '') {
        return trimmed.substring(0, 100); // Limit to 100 chars
      }
    }

    return 'Untitled';
  }
}

// Singleton instance
let instance: MarkdownService | null = null;

/**
 * Get or create markdown service instance
 */
export function getMarkdownService(): MarkdownService {
  instance ??= new MarkdownService();
  return instance;
}

/**
 * Minimal HTML → Markdown converter for Node (no DOM available).
 * Handles common tags we generate: headings, paragraphs, strong/em, links,
 * images, lists, breaks, inline and fenced code blocks.
 */
function simpleHtmlToMarkdown(input: string): string {
  let out = input;

  // Normalize whitespace around block tags
  out = out.replaceAll('\r\n', '\n');

  // Note links: <span data-type="note-link" data-title="Note Name">Note Name</span>
  // Process early before stripTags is called on paragraph content
  out = out.replaceAll(
    /<span[^>]*data-type=["']note-link["'][^>]*data-title=["']([^"']+)["'][^>]*>[^<]*<\/span>/gi,
    (_, title: string) => `[[${decodeHtmlEntities(title)}]]`,
  );

  // Code blocks: <pre><code class="language-xyz">...</code></pre>
  out = out.replaceAll(
    /<pre>\s*<code([^>]*)>([\s\S]*?)<\/code>\s*<\/pre>/gi,
    (_, attrs: string, code: string) => {
      const langMatch = /class=["']?[^"']*language-([\w-]+)/i.exec(attrs);
      const lang = langMatch ? langMatch[1] : '';
      // Decode HTML entities inside code
      const decoded = decodeHtmlEntities(code);
      return `\n\n\`\`\`${lang}\n${decoded}\n\`\`\`\n\n`;
    },
  );

  // Indented headings (with data-indent attribute) - handle before regular headings
  for (let i = 6; i >= 1; i--) {
    const indentRe = new RegExp(String.raw`<h${i}[^>]*data-indent=["'](\d+)["'][^>]*>([\s\S]*?)<\/h${i}>`, 'gi');
    out = out.replaceAll(
      indentRe,
      (_, indent: string, text: string) => {
        const tabs = '\t'.repeat(Number.parseInt(indent, 10));
        return `\n\n${tabs}${'#'.repeat(i)} ${stripTags(text).trim()}\n\n`;
      },
    );
  }

  // Regular headings (without indent)
  for (let i = 6; i >= 1; i--) {
    const re = new RegExp(String.raw`<h${i}[^>]*>([\s\S]*?)<\/h${i}>`, 'gi');
    out = out.replaceAll(
      re,
      (_, text: string) => `\n\n${'#'.repeat(i)} ${stripTags(text).trim()}\n\n`,
    );
  }

  // Indented paragraphs (with data-indent attribute)
  out = out.replaceAll(
    /<p[^>]*data-indent=["'](\d+)["'][^>]*>([\s\S]*?)<\/p>/gi,
    (_, indent: string, text: string) => {
      const tabs = '\t'.repeat(Number.parseInt(indent, 10));
      return `\n\n${tabs}${stripTags(text).trim()}\n\n`;
    },
  );

  // Regular paragraphs
  out = out.replaceAll(
    /<p[^>]*>([\s\S]*?)<\/p>/gi,
    (_, text: string) => `\n\n${stripTags(text).trim()}\n\n`,
  );

  // Line breaks
  out = out.replaceAll(/<br\s*\/?>(\s*)/gi, '\n');

  // Task lists with Logseq-style states (WITH dash prefix for consistency)
  out = out.replaceAll(
    /<li[^>]*data-type=["']taskItem["'][^>]*data-state=["']([^"']+)["'][^>]*>([\s\S]*?)<\/li>/gi,
    (_, state: string, content: string) => {
      const stateLabel = state.toUpperCase();
      // Remove the button element and extract text from div/p
      const textContent = content
        .replaceAll(/<button[^>]*>[\s\S]*?<\/button>/gi, '')
        .replaceAll(/<div[^>]*>([\s\S]*?)<\/div>/gi, '$1')
        .replaceAll(/<p[^>]*>([\s\S]*?)<\/p>/gi, '$1')
        .trim();
      // Save as list-style task item with dash prefix for consistency
      return `- ${stateLabel} ${stripTags(textContent)}\n`;
    },
  );

  // Unordered lists
  out = out.replaceAll(/<ul[^>]*>([\s\S]*?)<\/ul>/gi, (_, inner: string) => {
    const items = inner
      .replaceAll('\n', ' ')
      .split(/<li[^>]*>/i)
      .map((s: string) => s.replaceAll('</li>', '').trim())
      .filter(Boolean);
    const formatted = items.map((it: string) => '- ' + stripTags(it));
    return '\n\n' + formatted.join('\n') + '\n\n';
  });

  // Ordered lists
  out = out.replaceAll(/<ol[^>]*>([\s\S]*?)<\/ol>/gi, (_, inner: string) => {
    const items = inner
      .replaceAll('\n', ' ')
      .split(/<li[^>]*>/i)
      .map((s: string) => s.replaceAll('</li>', '').trim())
      .filter(Boolean);
    const formatted = items.map((it: string, idx: number) => (idx + 1) + '. ' + stripTags(it));
    return '\n\n' + formatted.join('\n') + '\n\n';
  });

  // Images (bounded quantifiers prevent ReDoS)
  out = out.replaceAll(
    /<img\s{1,10}[^>]{0,500}src=["']([^"']{1,2000})["'][^>]{0,500}alt=["']([^"']{0,500})["'][^>]{0,500}\/?>(?:<\/img>)?/gi,
    (_, src: string, alt: string) => `![${alt}](${src})`,
  );
  out = out.replaceAll(
    /<img\s{1,10}[^>]{0,500}alt=["']([^"']{0,500})["'][^>]{0,500}src=["']([^"']{1,2000})["'][^>]{0,500}\/?>(?:<\/img>)?/gi,
    (_, alt: string, src: string) => `![${alt}](${src})`,
  );

  // Links (bounded quantifiers prevent ReDoS)
  out = out.replaceAll(
    /<a\s{1,10}[^>]{0,500}href=["']([^"']{1,2000})["'][^>]{0,500}>([\s\S]{0,10000}?)<\/a>/gi,
    (_, href: string, text: string) => `[${stripTags(text)}](${href})`,
  );

  // Inline code
  out = out.replaceAll(
    /<code[^>]*>([\s\S]*?)<\/code>/gi,
    (_, code: string) => `\`${stripTags(decodeHtmlEntities(code))}\``,
  );

  // Emphasis and strong
  out = out.replaceAll(/<strong[^>]*>([\s\S]*?)<\/strong>/gi, (_, t: string) => `**${stripTags(t)}**`);
  out = out.replaceAll(/<b[^>]*>([\s\S]*?)<\/b>/gi, (_, t: string) => `**${stripTags(t)}**`);
  out = out.replaceAll(/<em[^>]*>([\s\S]*?)<\/em>/gi, (_, t: string) => `*${stripTags(t)}*`);
  out = out.replaceAll(/<i[^>]*>([\s\S]*?)<\/i>/gi, (_, t: string) => `*${stripTags(t)}*`);

  // Finally strip any remaining tags
  out = stripTags(out);

  // Collapse excess blank lines
  out = out.replaceAll(/\n{3,}/g, '\n\n').trim();

  return out;
}

function stripTags(s: string): string {
  return s.replaceAll(/<[^>]{1,1000}>/g, '');
}

function decodeHtmlEntities(s: string): string {
  return s
    .replaceAll('&lt;', '<')
    .replaceAll('&gt;', '>')
    .replaceAll('&amp;', '&')
    .replaceAll('&quot;', '"')
    .replaceAll('&#39;', "'");
}

function escapeHtml(s: string): string {
  return s
    .replaceAll('&', '&amp;')
    .replaceAll('<', '&lt;')
    .replaceAll('>', '&gt;')
    .replaceAll('"', '&quot;')
    .replaceAll("'", '&#39;');
}
