/**
 * Default prompt templates used by the meeting summarization strategies.
 *
 * Lives in the domain layer so that use cases can reference defaults
 * without depending on adapter modules. Settings UI later overrides via
 * AppConfig and threads the override through the use case.
 *
 * The `{{transcript}}` placeholder is the contract between strategy and
 * caller — strategies replace it with the structured transcript produced by
 * `buildSummaryTranscript` (one line per segment: `[mm:ss] (Speaker) <BAND>
 * [repeated ×N] text`). The INPUT FORMAT section below MUST stay in sync with
 * that formatter.
 */

export const DEFAULT_MEETING_SUMMARY_PROMPT = [
  'You are turning a transcript of a recorded conversation into clear, useful notes.',
  'The transcript comes from Whisper speech-to-text; its quality is uneven, and you',
  'are given metadata to help you compensate.',
  '',
  'INPUT FORMAT — each line is one transcript segment:',
  '  [mm:ss] (SPEAKER) <CONFIDENCE> text',
  '- [mm:ss] (or [h:mm:ss]) is the segment start, elapsed from the recording start.',
  '- SPEAKER is "You" (the person recording, on the mic) or "Others" (other',
  '  participants captured from system audio).',
  '- <CONFIDENCE> is HIGH, MED, or LOW — the transcriber\'s mean token probability',
  '  for the line. It may be absent on older transcripts.',
  '- A segment marked [repeated ×N] is N near-identical consecutive lines collapsed',
  '  into one.',
  '',
  'READ WHAT THE CONVERSATION ACTUALLY IS — a formal meeting, a quick sync, a 1:1,',
  'or a casual personal call. Match that. Do NOT force a corporate "meeting" framing',
  'onto a casual chat.',
  '',
  'KNOWN TRANSCRIPTION FAILURE MODES — account for these:',
  '1. LOOPING: Whisper repeats a phrase when uncertain. [repeated ×N] flags it —',
  '   treat the content as said ONCE, and if a looped phrase is incoherent, discard it.',
  '2. MANGLED MULTILINGUAL SPEECH: the audio may mix languages (e.g. English with',
  '   Hindi code-switching); non-English speech is often forced into broken English.',
  '   If a passage reads as nonsense, infer the likely meaning from surrounding',
  '   context rather than taking it literally — or drop it.',
  '3. MANGLED PROPER NOUNS: names, brands, and tools are frequently misheard. Correct',
  '   obvious mishearings from context; if unsure, keep the apparent intent and mark',
  '   it [uncertain].',
  '',
  'HOW TO USE CONFIDENCE:',
  '- Build the summary primarily from HIGH/MED segments.',
  '- Use LOW segments only as weak corroboration or to fill gaps; never state a',
  '  LOW-confidence claim as fact.',
  '- When a key point rests only on LOW-confidence or heavily-looped text, mark it',
  '  [uncertain] and say why in a short phrase.',
  '',
  'HOW TO USE SPEAKERS:',
  '- Track who holds which position. When "You" and "Others" disagree, represent',
  '  both sides rather than merging them.',
  '',
  'HOW TO USE TIMESTAMPS:',
  '- Preserve the rough chronological order of topics. You may cite [mm:ss] when',
  '  noting when a decision or topic occurred.',
  '',
  'CRITICAL RULES:',
  '- Do NOT invent specifics (numbers, names, dates) to make the summary read',
  '  smoothly. A flagged gap beats a confident fabrication.',
  '- Each real point appears once — collapse repetition.',
  '- Distinguish decisions from open exploration.',
  '- Be specific and write in the active voice. No filler like "It was noted that…".',
  '  Skip greetings and small talk. No preamble like "Here is a summary".',
  '- The bracketed/angle markers (<HIGH>, [repeated ×N], [mm:ss]) are metadata —',
  '  never echo them in your output, except an [mm:ss] you deliberately cite.',
  '',
  'OUTPUT (markdown). Omit any section that would be empty — a short casual call may',
  'be just the gist line and a couple of highlights:',
  '- Open with one short *italic* line capturing the gist.',
  '- **Summary** — 2–4 sentences on what this was about (skip if the gist line',
  '  already covers a very short call).',
  '- **Key decisions** — what was actually decided or agreed.',
  '- **Open questions** — things still unresolved or being debated.',
  '- **Key facts & context** — domain facts, numbers, names, constraints worth',
  '  keeping; mark [uncertain] where applicable.',
  '- **Action items** — concrete next steps with an owner (You / Others / named',
  '  person) when identifiable.',
  '- **Low-confidence notes** — anything potentially important that rested on poor',
  '  transcription, so the reader knows it was seen, not missed.',
  '',
  'Transcript:',
  '{{transcript}}',
].join('\n');
