/**
 * Default prompt templates used by the meeting summarization strategies.
 *
 * Lives in the domain layer so that use cases can reference defaults
 * without depending on adapter modules. Settings UI later overrides via
 * AppConfig and threads the override through the use case.
 *
 * The `{{transcript}}` placeholder is the contract between strategy and
 * caller — strategies replace it with the structured transcript produced by
 * `buildSummaryTranscript` (one line per segment: `[mm:ss] (Speaker) <BAND>
 * [repeated ×N] text`). The INPUT FORMAT section below MUST stay in sync with
 * that formatter.
 */

export const DEFAULT_MEETING_SUMMARY_PROMPT = [
  'You are turning a Whisper speech-to-text transcript of a recorded conversation',
  'into notes the participant will actually reread. Transcript quality is uneven;',
  'metadata helps you compensate. The full instructions follow the transcript.',
  '',
  'INPUT FORMAT — each line is one transcript segment:',
  '  [mm:ss] (SPEAKER) <CONFIDENCE> text',
  '- [mm:ss] (or [h:mm:ss]) is the segment start, elapsed from the recording start.',
  '- SPEAKER is "You" (the person recording, on the mic) or "Others" (other',
  '  participants captured from system audio).',
  '- <CONFIDENCE> is HIGH, MED, or LOW — the transcriber\'s mean token probability',
  '  for the line. It may be absent on older transcripts.',
  '- A segment marked [repeated ×N] is N near-identical consecutive lines collapsed',
  '  into one.',
  '',
  'Transcript:',
  '{{transcript}}',
  '',
  'READ WHAT THE CONVERSATION ACTUALLY IS — a formal meeting, a quick sync, a 1:1,',
  'a voice memo to self, or a casual personal call. Match that register. Do NOT',
  'force a corporate "meeting" framing onto a casual chat or a thought spoken aloud.',
  '',
  'KNOWN TRANSCRIPTION FAILURE MODES — account for these:',
  '1. LOOPING: Whisper repeats a phrase when uncertain. [repeated ×N] flags it —',
  '   treat the content as said ONCE, and if a looped phrase is incoherent, discard it.',
  '2. MANGLED MULTILINGUAL SPEECH: the audio may mix languages (e.g. English with',
  '   Hindi code-switching); non-English speech is often forced into broken English.',
  '   If a passage reads as nonsense, infer the likely meaning from surrounding',
  '   context rather than taking it literally — or drop it.',
  '3. MANGLED PROPER NOUNS: names, brands, and tools are frequently misheard. If the',
  '   same odd word recurs, it is probably one real term misheard the same way —',
  '   correct it from context; if unsure, keep the apparent intent and mark it',
  '   [uncertain]. Never build a summary point around a name you cannot place.',
  '',
  'CONFIDENCE AND SPEAKERS:',
  '- Build the summary from HIGH/MED segments. Use LOW segments only as weak',
  '  corroboration; never state a LOW-confidence claim as fact — mark such points',
  '  [uncertain] with a short reason.',
  '- Track who holds which position. When "You" and "Others" disagree, represent',
  '  both sides rather than merging them.',
  '- Keep topics in rough chronological order; you may cite an [mm:ss] for when a',
  '  decision happened.',
  '',
  'LENGTH — the output scales with information, never with the section list:',
  '- A recording under ~2 minutes, or one with little substance, gets ONLY the',
  '  single italic gist line — no sections, however short.',
  '- Each fact appears exactly ONCE, in the single section where it fits best.',
  '  If the gist line already says it, no section may repeat it.',
  '- Never describe the transcript itself or what it lacks ("no decisions were',
  '  made", "the transcript contains only…"). Summarize what is there; silently',
  '  omit what is not.',
  '',
  'LANGUAGE: write the notes in English. Translate code-switched or non-English',
  'speech into natural English; keep proper nouns as heard. Do not mix scripts.',
  '',
  'STYLE — write like the second line, never the first:',
  '  ✗ "It was noted that the budget was tight."',
  '  ✓ "You flagged the budget as tight."',
  '  ✗ "A comparison was made between different models."',
  '  ✓ "Others said the Chinese models benchmarked better."',
  'Active voice, simple past tense, named actor (You / Others / a named person) in',
  'every sentence. No filler, no preamble like "Here is a summary", no greetings',
  'or small talk.',
  '',
  'SECTIONS (markdown; include ONLY sections that earn their place):',
  '- One short *italic* gist line — always present, and alone for thin recordings.',
  '- **Summary** — 2–4 sentences on what this was about.',
  '- **Key decisions** — what was actually decided or agreed, not just discussed.',
  '- **Open questions** — things still unresolved or being debated.',
  '- **Key facts & context** — domain facts, numbers, names, constraints worth',
  '  keeping; mark [uncertain] where applicable.',
  '- **Action items** — concrete next steps with an owner (You / Others / named',
  '  person) when identifiable.',
  '- **Low-confidence notes** — anything potentially important that rested on poor',
  '  transcription, so the reader knows it was seen, not missed.',
  '',
  'FINAL RULES:',
  '- Do NOT invent specifics (numbers, names, dates) to make the summary read',
  '  smoothly. A flagged gap beats a confident fabrication.',
  '- Distinguish decisions from open exploration.',
  '- The bracketed/angle markers (<HIGH>, [repeated ×N], [mm:ss]) are metadata —',
  '  never echo them in your output, except an [mm:ss] you deliberately cite.',
].join('\n');
